"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Presentation, Loader2, Sparkles, Download, Monitor, Layout as LayoutIcon, Trash2, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import axios from "axios";
import pptxgen from "pptxgenjs";

export default function PptGeneratorPage() {
    const [topic, setTopic] = useState("");
    const [generating, setGenerating] = useState(false);
    const [slides, setSlides] = useState<any[]>([]);
    const [downloaded, setDownloaded] = useState(false);

    const onGenerate = async () => {
        if (!topic) return;
        try {
            setGenerating(true);
            setSlides([]);
            setDownloaded(false);

            const res = await axios.post("/api/ppt/generate", { topic, pages: 10 });
            setSlides(res.data);
        } catch (error) {
            console.error(error);
        } finally {
            setGenerating(false);
        }
    };

    const downloadPPT = () => {
        if (slides.length === 0) return;

        const pres = new pptxgen();

        // Settings
        pres.layout = "LAYOUT_16x9";
        pres.author = "ResearchPro AI";
        pres.subject = topic;

        slides.forEach((slideData: any) => {
            const slide = pres.addSlide();

            // Background / design
            slide.background = { fill: "F5F7FA" };

            // Title
            slide.addText(slideData.title, {
                x: 0.5,
                y: 0.5,
                w: "90%",
                h: 1,
                fontSize: 32,
                bold: true,
                color: "1e293b",
                fontFace: "Arial"
            });

            // Content
            slideData.content.forEach((bullet: string, idx: number) => {
                slide.addText(bullet, {
                    x: 0.5,
                    y: 1.8 + (idx * 0.6),
                    w: "90%",
                    fontSize: 18,
                    color: "334155",
                    bullet: true,
                    fontFace: "Arial"
                });
            });

            // Footer
            slide.addText("Generated by ResearchPro AI", {
                x: 0.5,
                y: 5.2,
                w: "90%",
                fontSize: 10,
                color: "94a3b8",
                italic: true
            });
        });

        pres.writeFile({ fileName: `${topic.substring(0, 30).replace(/\s+/g, "_")}.pptx` });
        setDownloaded(true);
        setTimeout(() => setDownloaded(false), 3000);
    };

    return (
        <div className="p-6 space-y-8 max-w-7xl mx-auto">
            <div className="flex flex-col gap-y-2">
                <div className="flex items-center gap-x-3">
                    <div className="p-2 bg-red-100 rounded-lg">
                        <Presentation className="w-8 h-8 text-red-600" />
                    </div>
                    <h1 className="text-3xl font-bold tracking-tight">AI Presentation Generator</h1>
                </div>
                <p className="text-muted-foreground">
                    Convert your research topic into a professional academic presentation instantly.
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Control Panel */}
                <Card className="lg:col-span-5 shadow-sm border-none bg-muted/5">
                    <CardHeader>
                        <CardTitle>Presentation Settings</CardTitle>
                        <CardDescription>Enter your topic and we will design the slides for you.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="space-y-2">
                            <label className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">Research Topic / Title</label>
                            <textarea
                                className="w-full h-32 p-4 bg-background border rounded-2xl focus:ring-2 focus:ring-red-500 focus:outline-none transition-all resize-none shadow-inner"
                                placeholder="e.g. The Impact of Blockchain on Supply Chain Transparency..."
                                value={topic}
                                onChange={(e) => setTopic(e.target.value)}
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="p-4 border bg-background rounded-2xl flex items-center gap-x-3 border-red-500/20 shadow-sm">
                                <Monitor className="w-5 h-5 text-red-500" />
                                <div className="text-left">
                                    <p className="text-xs font-bold">Wide Screen</p>
                                    <p className="text-[10px] text-muted-foreground">16:9 Optimized</p>
                                </div>
                            </div>
                            <div className="p-4 border bg-background rounded-2xl flex items-center gap-x-3 border-transparent">
                                <LayoutIcon className="w-5 h-5 text-muted-foreground" />
                                <div className="text-left">
                                    <p className="text-xs font-bold">Academic Style</p>
                                    <p className="text-[10px] text-muted-foreground">Pro-Dissertation</p>
                                </div>
                            </div>
                        </div>

                        <Button
                            className="w-full h-12 bg-red-600 hover:bg-red-700 font-bold rounded-xl shadow-lg shadow-red-500/20"
                            onClick={onGenerate}
                            disabled={generating || !topic}
                        >
                            {generating ? (
                                <>
                                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                    AI is Designing Slides...
                                </>
                            ) : (
                                <>
                                    <Sparkles className="w-4 h-4 mr-2" />
                                    Create Presentation
                                </>
                            )}
                        </Button>
                    </CardContent>
                </Card>

                {/* Preview / Results Area */}
                <div className="lg:col-span-7 space-y-6">
                    {slides.length > 0 ? (
                        <div className="space-y-4 animate-in fade-in slide-in-from-right-4">
                            <div className="flex items-center justify-between px-2">
                                <h2 className="text-lg font-bold">Created Slides ({slides.length})</h2>
                                <Button
                                    onClick={downloadPPT}
                                    className={`rounded-xl shadow-lg transition-all ${downloaded ? "bg-emerald-500 hover:bg-emerald-600" : "bg-slate-900 hover:bg-black shadow-slate-900/10"}`}
                                >
                                    {downloaded ? (
                                        <><CheckCircle2 className="w-4 h-4 mr-2" /> Downloaded!</>
                                    ) : (
                                        <><Download className="w-4 h-4 mr-2" /> Download .PPTX</>
                                    )}
                                </Button>
                            </div>

                            <div className="grid grid-cols-1 gap-4 overflow-y-auto max-h-[600px] pr-2 custom-scrollbar">
                                {slides.map((slide, i) => (
                                    <div key={i} className="bg-white border-2 border-slate-100 rounded-2xl p-6 shadow-sm hover:border-red-500/30 transition-all group">
                                        <div className="flex items-start justify-between mb-4">
                                            <span className="text-[10px] font-black text-slate-300 uppercase">Slide {i + 1}</span>
                                            <h3 className="text-md font-black text-slate-800 tracking-tight group-hover:text-red-600 transition-colors uppercase">{slide.title}</h3>
                                        </div>
                                        <ul className="space-y-2">
                                            {slide.content.map((point: string, j: number) => (
                                                <li key={j} className="text-xs text-slate-500 flex items-start gap-x-2">
                                                    <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-red-400 flex-shrink-0" />
                                                    {point}
                                                </li>
                                            ))}
                                        </ul>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ) : (
                        <div className="h-[500px] border-2 border-dashed border-slate-200 rounded-[2rem] flex flex-col items-center justify-center text-center p-12 opacity-40">
                            <Presentation className="w-16 h-16 text-slate-300 mb-4" />
                            <h2 className="text-xl font-bold text-slate-400">Preview Area</h2>
                            <p className="text-sm text-slate-400 max-w-xs">Your AI-generated slides will appear here after design is complete.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
